"""initial schema

Revision ID: fb916193e1bc
Revises:
Create Date: 2026-04-05 19:47:41.418431

"""

from collections.abc import Sequence

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

from alembic import op
from app.core.encryption import EncryptedString

# revision identifiers, used by Alembic.
revision: str = "fb916193e1bc"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "counties",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=False),
        sa.Column("fips_code", sa.String(length=10), nullable=True),
        sa.Column("source_url", sa.String(length=1024), nullable=True),
        sa.Column("source_type", sa.String(length=10), nullable=True),
        sa.Column("scraper_class", sa.String(length=255), nullable=True),
        sa.Column("scrape_schedule", sa.String(length=100), nullable=True),
        sa.Column("last_scraped_at", sa.DateTime(), nullable=True),
        sa.Column("last_lead_count", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "state", name="uq_county_name_state"),
    )
    op.create_table(
        "failed_tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.String(length=255), nullable=False),
        sa.Column("task_name", sa.String(length=255), nullable=False),
        sa.Column("args", sa.JSON(), nullable=True),
        sa.Column("exception", sa.Text(), nullable=True),
        sa.Column("traceback", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "letter_templates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("letter_type", sa.String(length=50), nullable=False),
        sa.Column("template_body", sa.Text(), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("clerk_id", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", EncryptedString(length=1024), nullable=False),
        sa.Column("company_name", EncryptedString(length=1024), nullable=True),
        sa.Column("phone", EncryptedString(length=512), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("stripe_customer_id", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_clerk_id"), "users", ["clerk_id"], unique=True)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "leads",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("county_id", sa.Uuid(), nullable=False),
        sa.Column("case_number", sa.String(length=100), nullable=False),
        sa.Column("parcel_id", sa.String(length=100), nullable=True),
        sa.Column("property_address", sa.String(length=500), nullable=True),
        sa.Column("property_city", sa.String(length=255), nullable=True),
        sa.Column("property_state", sa.String(length=2), nullable=True),
        sa.Column("property_zip", sa.String(length=10), nullable=True),
        sa.Column("surplus_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("sale_date", sa.Date(), nullable=True),
        sa.Column("sale_type", sa.String(length=20), nullable=True),
        sa.Column("owner_name", EncryptedString(length=1024), nullable=True),
        sa.Column("owner_last_known_address", EncryptedString(length=2048), nullable=True),
        sa.Column("source_hash", sa.String(length=64), nullable=False),
        sa.Column("raw_data", sa.JSON(), nullable=True),
        sa.Column("embedding", Vector(384), nullable=True),
        sa.Column("archived_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("surplus_amount >= 0", name="ck_lead_surplus_positive"),
        sa.ForeignKeyConstraint(
            ["county_id"],
            ["counties.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("county_id", "case_number", name="uq_lead_county_case"),
    )
    op.create_index("ix_leads_county_id", "leads", ["county_id"], unique=False)
    op.create_index(
        "ix_leads_sale_date", "leads", ["sale_date"], unique=False, postgresql_using="btree"
    )
    op.create_index("ix_leads_source_hash", "leads", ["source_hash"], unique=False)
    op.create_index(
        "ix_leads_surplus_amount",
        "leads",
        ["surplus_amount"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_table(
        "llm_usage",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("task_type", sa.String(length=20), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("estimated_cost", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "skip_trace_credits",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("credits_remaining", sa.Integer(), nullable=False),
        sa.Column("credits_used_this_month", sa.Integer(), nullable=False),
        sa.Column("reset_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("stripe_subscription_id", sa.String(length=255), nullable=True),
        sa.Column("plan", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("current_period_start", sa.DateTime(), nullable=True),
        sa.Column("current_period_end", sa.DateTime(), nullable=True),
        sa.Column("billing_interval", sa.String(length=10), nullable=True),
        sa.Column("skip_trace_credits_monthly", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_subscription_user_active",
        "subscriptions",
        ["user_id"],
        unique=True,
        postgresql_where="status IN ('active', 'trialing')",
    )
    op.create_table(
        "lead_activities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("activity_type", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_lead_activities_lead_user_created",
        "lead_activities",
        ["lead_id", "user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "lead_contacts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column("contact_type", sa.String(length=20), nullable=False),
        sa.Column("contact_value", EncryptedString(length=1024), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("confidence BETWEEN 0 AND 1", name="ck_contact_confidence"),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "letters",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=True),
        sa.Column("letter_type", sa.String(length=50), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["letter_templates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_leads",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("quality_score", sa.Integer(), nullable=True),
        sa.Column("quality_reasoning", sa.Text(), nullable=True),
        sa.Column("priority", sa.String(length=10), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("quality_score BETWEEN 1 AND 10", name="ck_user_lead_quality_score"),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "lead_id", name="uq_user_lead"),
    )
    op.create_index(
        "ix_user_leads_quality_score",
        "user_leads",
        ["quality_score"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index("ix_user_leads_user_status", "user_leads", ["user_id", "status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_leads_user_status", table_name="user_leads")
    op.drop_index("ix_user_leads_quality_score", table_name="user_leads", postgresql_using="btree")
    op.drop_table("user_leads")
    op.drop_table("letters")
    op.drop_table("lead_contacts")
    op.drop_index("ix_lead_activities_lead_user_created", table_name="lead_activities")
    op.drop_table("lead_activities")
    op.drop_index(
        "uq_subscription_user_active",
        table_name="subscriptions",
        postgresql_where="status IN ('active', 'trialing')",
    )
    op.drop_table("subscriptions")
    op.drop_table("skip_trace_credits")
    op.drop_table("llm_usage")
    op.drop_index("ix_leads_surplus_amount", table_name="leads", postgresql_using="btree")
    op.drop_index("ix_leads_source_hash", table_name="leads")
    op.drop_index("ix_leads_sale_date", table_name="leads", postgresql_using="btree")
    op.drop_index("ix_leads_county_id", table_name="leads")
    op.drop_table("leads")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_clerk_id"), table_name="users")
    op.drop_table("users")
    op.drop_table("letter_templates")
    op.drop_table("failed_tasks")
    op.drop_table("counties")
    # ### end Alembic commands ###
