"""activate FL 5 remaining scrapable counties — Broward, Hillsborough, Martin, Collier, Okaloosa

Revision ID: y1z2a3b4c5d6
Revises: p2q3r4s5t6u7
Create Date: 2026-04-15 12:00:00.000000

Activates 5 Florida counties that were classified as "Scrapable" in the
county surplus research CSV but had not yet been wired up.

─────────────────────────────────────────────────────────────────────────────
Broward County — broward.org
─────────────────────────────────────────────────────────────────────────────
Scraper: CloudscraperHtmlScraper
URL: https://www.broward.org/RecordsTaxesTreasury/TaxesFees/Pages/Overbid.aspx
Format: HTML table (4 columns: Case Number, Owner Name, Surplus Amount, Property Address)
Config: col defaults 0/1/2/3; table_selector="table"
Verified: 5 leads in synthetic fixture (broward_overbid.html) as of 2026-04-15.
Note: The broward.org domain returns 403 / SSL errors to plain requests. The
  scraper is set to CloudscraperHtmlScraper, which bypasses Cloudflare via a
  TLS-fingerprint-spoof session. SSL cert warnings are suppressed (verify=False
  already default in CloudscraperHtmlScraper.fetch).

─────────────────────────────────────────────────────────────────────────────
Hillsborough County — hillsclerk.com
─────────────────────────────────────────────────────────────────────────────
Scraper: XlsxScraper (claims mode)
source_url: https://www.hillsclerk.com/departments/county-civil/tax-deeds/
  (via ParentPageXlsxScraper — the actual XLSX URL rotates with a date in the filename)
Format: XLSX, claims mode (not simple_table_mode)
Columns: FILE# (col 0 → case_number), claims text column (col 1, regex-extracted owner + amount)
xlsx_link_pattern: "(?i)ada.*td.*claim|td.*claim.*info|ada-accessible"
  matches filenames like "ada-accessible-td-claim-info-master-10-13-2025-2.xlsx"
Verified: >10 leads in existing fixture (hillsborough_surplus.xlsx) as of 2026-04-15.
Note: URL rotates with date in filename each time the clerk publishes an update.
  check_county_urls.py will alert when the current URL is stale. When that
  happens, browse the parent page to find the updated link.
  Active URL at time of migration:
    https://www.hillsclerk.com/documents/d/guest/ada-accessible-td-claim-info-master-10-13-2025-2

─────────────────────────────────────────────────────────────────────────────
Martin County — martinclerk.com
─────────────────────────────────────────────────────────────────────────────
Scraper: PdfScraper (text_line_mode)
URL: https://martinclerk.com/DocumentCenter/View/517/Tax-Deed-Overbid-List-PDF
Format: WordPress-hosted PDF, one record per text line (no tabular structure)
Line format: <CASE_NUM> $<AMOUNT> <DATE> <OWNER_NAME>
  Example: 2022-TDA-001 $5,234.56 01/15/2022 JOHN SMITH PROPERTIES LLC
Pattern: ^(?P<case>\\d{4}-TDA-\\d+)\\s+\\$\\s*(?P<amt>[\\d,]+\\.\\d{2})\\s+
         (?P<date>\\d{1,2}/\\d{1,2}/\\d{4})\\s+(?P<owner>.+)$
Fields map: case→case_number, amt→surplus_amount, owner→owner_name, date→sale_date
Verified: 3 leads in synthetic fixture (fl_martin_overbid.pdf) as of 2026-04-15.
  Live lead count pending first production run.

─────────────────────────────────────────────────────────────────────────────
Collier County — app.collierclerk.com (reactivation note)
─────────────────────────────────────────────────────────────────────────────
Scraper: PdfScraper (table mode)
URL: https://app.collierclerk.com/LFOfficialRecords/edoc/6476/
     Tax%20Deed%20Sales%20Excess%20Proceeds%20List.pdf?dbid=0&repo=OFFICIALRECORDSPROD
Format: Laserfiche-served PDF, 11 columns (Excel-generated by clerk's office)
Column layout (0-indexed):
  0: Sale Date
  1: TDA #           → case_number
  2: Surplus         → surplus_amount
  3: Claim Pending
  4: Day Deadline
  5: Legal Titleholder (prior to sale) → owner_name
  6: Address         → property_address
  7: City
  8: State / Zip
  9: Property ID#
  10: Legal Description
skip_rows_containing: ["Sale Date", "TDA #", "Surplus", "Claim Pending", "Legal Titleholder"]
Verified: 120 unclaimed surplus records as of 2026-01-29, sale dates 7/2024–12/2024.
  Doc ID 6476 is stable across Laserfiche version uploads.
Note: If URL breaks, check_county_urls.py will alert, then find the new doc ID
  via Playwright on www.collierclerk.com/tax-deed-sales/tax-deed-surplus/.
Previous deactivation (i4h5g6f7e8d9): ParentPagePdfScraper's pdf_link_pattern
  matched no href on the collierclerk.com landing page (page returns 403 to
  non-browser traffic). Fix: use the direct Laserfiche PDF URL (edoc/6476).
This migration re-asserts the same config as p2q3r4s5t6u7 for completeness;
  the DB row should already be active — the UPDATE is idempotent.

─────────────────────────────────────────────────────────────────────────────
Okaloosa County — okaloosaclerk.com
─────────────────────────────────────────────────────────────────────────────
Scraper: PlaywrightHtmlScraper
URL: https://okaloosaclerk.com/board-services/tax-deed-sales/tax-deed-surplus/
Format: WordPress page with a Microsoft Power BI iframe link (app.powerbigov.us)
Config: col_case=0, col_owner=1, col_surplus=2, wait_ms=8000, wait_until="networkidle"
Verified: 0 leads from static HTML (Power BI requires JS rendering)
  Live lead count pending first production run — depends on Power BI iframe
  rendering within the 8s wait budget.
Note: The surplus data is served via Power BI, not an HTML table in the page
  source. PlaywrightHtmlScraper launches Chromium and waits for networkidle
  before extracting any rendered table. If the Power BI embed requires
  additional authentication or a longer load time, the scraper may return 0
  leads. An alternative approach is to request a direct data export from the
  Okaloosa Clerk's office (contact: board-services@okaloosaclerk.com).
"""

from __future__ import annotations

import json
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "y1z2a3b4c5d6"
down_revision: str | Sequence[str] | None = "p2q3r4s5t6u7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_BROWARD_URL = (
    "https://www.broward.org/RecordsTaxesTreasury/TaxesFees/Pages/Overbid.aspx"
)

_BROWARD_CONFIG = {
    "table_selector": "table",
    "col_case": 0,
    "col_owner": 1,
    "col_surplus": 2,
    "col_address": 3,
    "notes": (
        "Activated 2026-04-15. CloudscraperHtmlScraper bypasses Cloudflare 403 "
        "on broward.org. 4-column HTML table: col 0=Case Number, col 1=Owner Name, "
        "col 2=Surplus Amount, col 3=Property Address. "
        "5 leads verified in broward_overbid.html fixture."
    ),
}

_HILLSBOROUGH_PARENT_URL = "https://www.hillsclerk.com/departments/county-civil/tax-deeds/"

_HILLSBOROUGH_CONFIG = {
    "xlsx_link_pattern": r"(?i)ada.*td.*claim|td.*claim.*info|ada-accessible",
    "extract_from_claims": True,
    "notes": (
        "Activated 2026-04-15. URL rotates with date in filename each time the "
        "clerk publishes an update. ParentPageXlsxScraper fetches the parent page "
        "and follows the link matching xlsx_link_pattern. "
        "Active URL at migration time: "
        "https://www.hillsclerk.com/documents/d/guest/"
        "ada-accessible-td-claim-info-master-10-13-2025-2. "
        "check_county_urls.py will alert when stale. "
        ">10 leads verified in hillsborough_surplus.xlsx fixture."
    ),
}

_MARTIN_URL = (
    "https://martinclerk.com/DocumentCenter/View/517/Tax-Deed-Overbid-List-PDF"
)

_MARTIN_CONFIG = {
    "text_line_mode": True,
    "line_pattern": (
        r"^(?P<case>\d{4}-TDA-\d+)\s+"
        r"\$\s*(?P<amt>[\d,]+\.\d{2})\s+"
        r"(?P<date>\d{1,2}/\d{1,2}/\d{4})\s+"
        r"(?P<owner>.+)$"
    ),
    "fields": {
        "case": "case_number",
        "amt": "surplus_amount",
        "owner": "owner_name",
        "date": "sale_date",
    },
    "notes": (
        "Activated 2026-04-15. WordPress-hosted PDF, one record per text line. "
        "Line format: <CASE_NUM> $<AMOUNT> <DATE> <OWNER_NAME>. "
        "3 leads verified in fl_martin_overbid.pdf synthetic fixture. "
        "Live lead count pending first production run."
    ),
}

_COLLIER_URL = (
    "https://app.collierclerk.com/LFOfficialRecords/edoc/6476/"
    "Tax%20Deed%20Sales%20Excess%20Proceeds%20List.pdf"
    "?dbid=0&repo=OFFICIALRECORDSPROD"
)

_COLLIER_CONFIG = {
    "columns": {
        "case_number": 1,
        "owner_name": 5,
        "surplus_amount": 2,
        "property_address": 6,
    },
    "skip_rows_containing": [
        "Sale Date",
        "TDA #",
        "Surplus",
        "Claim Pending",
        "Legal Titleholder",
    ],
    "notes": (
        "Config re-asserted 2026-04-15 (idempotent; initially activated by "
        "p2q3r4s5t6u7). Direct Laserfiche PDF URL — doc ID 6476 stable across "
        "version uploads. 11-col table: col 1=TDA#, col 2=Surplus$, "
        "col 5=Titleholder, col 6=Address. 120 records as of 2026-01-29. "
        "If URL breaks, find new doc ID via Playwright on "
        "www.collierclerk.com/tax-deed-sales/tax-deed-surplus/."
    ),
}

_OKALOOSA_URL = (
    "https://okaloosaclerk.com/board-services/tax-deed-sales/tax-deed-surplus/"
)

_OKALOOSA_CONFIG = {
    "col_case": 0,
    "col_owner": 1,
    "col_surplus": 2,
    "wait_ms": 8000,
    "wait_until": "networkidle",
    "notes": (
        "Activated 2026-04-15. Surplus data is embedded in a Microsoft Power BI "
        "iframe (app.powerbigov.us) — no HTML table in static page source. "
        "PlaywrightHtmlScraper waits 8s for networkidle so Chromium can render "
        "the iframe. Live lead count pending first production run. "
        "If Power BI requires authentication or longer load time, consider "
        "requesting a direct export from board-services@okaloosaclerk.com."
    ),
}


def upgrade() -> None:
    conn = op.get_bind()

    # Broward — CloudscraperHtmlScraper
    result = conn.execute(
        sa.text(
            "UPDATE counties "
            "SET is_active = true, "
            "    source_url = :url, "
            "    source_type = 'html', "
            "    scraper_class = 'CloudscraperHtmlScraper', "
            "    scrape_schedule = '0 3 * * *', "
            "    config = CAST(:cfg AS JSON) "
            "WHERE name = 'Broward' AND state = 'FL'"
        ),
        {"url": _BROWARD_URL, "cfg": json.dumps(_BROWARD_CONFIG)},
    )
    if result.rowcount != 1:
        raise RuntimeError(
            f"Expected exactly 1 row for Broward, FL — got {result.rowcount}"
        )

    # Hillsborough — ParentPageXlsxScraper (URL rotates; scraper follows link from parent page)
    result = conn.execute(
        sa.text(
            "UPDATE counties "
            "SET is_active = true, "
            "    source_url = :url, "
            "    source_type = 'xlsx', "
            "    scraper_class = 'ParentPageXlsxScraper', "
            "    scrape_schedule = '0 4 * * *', "
            "    config = CAST(:cfg AS JSON) "
            "WHERE name = 'Hillsborough' AND state = 'FL'"
        ),
        {"url": _HILLSBOROUGH_PARENT_URL, "cfg": json.dumps(_HILLSBOROUGH_CONFIG)},
    )
    if result.rowcount != 1:
        raise RuntimeError(
            f"Expected exactly 1 row for Hillsborough, FL — got {result.rowcount}"
        )

    # Martin — PdfScraper text_line_mode
    result = conn.execute(
        sa.text(
            "UPDATE counties "
            "SET is_active = true, "
            "    source_url = :url, "
            "    source_type = 'pdf', "
            "    scraper_class = 'PdfScraper', "
            "    scrape_schedule = '0 5 * * *', "
            "    config = CAST(:cfg AS JSON) "
            "WHERE name = 'Martin' AND state = 'FL'"
        ),
        {"url": _MARTIN_URL, "cfg": json.dumps(_MARTIN_CONFIG)},
    )
    if result.rowcount != 1:
        raise RuntimeError(
            f"Expected exactly 1 row for Martin, FL — got {result.rowcount}"
        )

    # Collier — PdfScraper table mode (idempotent re-assert)
    result = conn.execute(
        sa.text(
            "UPDATE counties "
            "SET is_active = true, "
            "    source_url = :url, "
            "    source_type = 'pdf', "
            "    scraper_class = 'PdfScraper', "
            "    scrape_schedule = '0 4 * * *', "
            "    config = CAST(:cfg AS JSON) "
            "WHERE name = 'Collier' AND state = 'FL'"
        ),
        {"url": _COLLIER_URL, "cfg": json.dumps(_COLLIER_CONFIG)},
    )
    if result.rowcount != 1:
        raise RuntimeError(
            f"Expected exactly 1 row for Collier, FL — got {result.rowcount}"
        )

    # Okaloosa — PlaywrightHtmlScraper (Power BI iframe)
    result = conn.execute(
        sa.text(
            "UPDATE counties "
            "SET is_active = true, "
            "    source_url = :url, "
            "    source_type = 'html', "
            "    scraper_class = 'PlaywrightHtmlScraper', "
            "    scrape_schedule = '0 6 * * *', "
            "    config = CAST(:cfg AS JSON) "
            "WHERE name = 'Okaloosa' AND state = 'FL'"
        ),
        {"url": _OKALOOSA_URL, "cfg": json.dumps(_OKALOOSA_CONFIG)},
    )
    if result.rowcount != 1:
        raise RuntimeError(
            f"Expected exactly 1 row for Okaloosa, FL — got {result.rowcount}"
        )


def downgrade() -> None:
    conn = op.get_bind()

    # Deactivate the 4 counties this migration introduced.
    for name in ["Broward", "Hillsborough", "Martin", "Okaloosa"]:
        conn.execute(
            sa.text(
                "UPDATE counties "
                "SET is_active = false, "
                "    source_url = NULL, source_type = NULL, scraper_class = NULL, "
                "    scrape_schedule = NULL, config = NULL "
                "WHERE name = :name AND state = 'FL'"
            ),
            {"name": name},
        )

    # Collier was already active (via p2q3r4s5t6u7) before this migration ran.
    # Restore it to that prior state rather than nulling it, so a rollback does
    # not silently stop Collier scraping.
    conn.execute(
        sa.text(
            "UPDATE counties "
            "SET is_active = true, "
            "    source_url = :url, "
            "    source_type = 'pdf', "
            "    scraper_class = 'PdfScraper', "
            "    scrape_schedule = '0 4 * * *', "
            "    config = CAST(:cfg AS JSON) "
            "WHERE name = 'Collier' AND state = 'FL'"
        ),
        {"url": _COLLIER_URL, "cfg": json.dumps(_COLLIER_CONFIG)},
    )
