"""Fixture-based tests for Texas county excess-proceeds scrapers.

These tests load real PDF bytes from saved fixture files and call
scraper.parse(bytes) directly — no mocking of pdfplumber.

Fixture files are generated by:
    python tests/fixtures/generate_tx_fixtures.py

Counties covered:
    - Dallas        → TexasPositionalPdfScraper (positional text layout)
    - Fort Bend     → PdfScraper (table mode, 7 columns)
    - Denton        → PdfScraper (table mode, 4 columns + multi-row header)
    - Galveston     → ParentPagePdfScraper (text_line_mode)
    - Young         → ParentPagePdfScraper (table mode, no owner)
    - Houston (TX)  → ParentPagePdfScraper (table mode, no owner)
"""

from __future__ import annotations

from decimal import Decimal
from pathlib import Path

import pytest

from app.ingestion.parent_page_pdf_scraper import ParentPagePdfScraper
from app.ingestion.pdf_scraper import PdfScraper
from app.ingestion.texas_scraper import TexasPositionalPdfScraper

FIXTURES = Path(__file__).parent.parent / "fixtures"


# ─── Dallas County — TexasPositionalPdfScraper ────────────────────────────────


class TestDallasFixture:
    """Dallas County: positional-text PDF where amounts contain internal spaces."""

    _FIXTURE = FIXTURES / "texas_dallas_excess_funds.pdf"

    _CONFIG = {
        "pdf_link_pattern": "ExcessFunds",
        "base_url": "https://www.dallascounty.org",
        "case_pattern": r"TX-\d{2}-\d{5}",
        "amount_keywords": ["SHERIFF", "CONSTABLE"],
    }

    def _make_scraper(self) -> TexasPositionalPdfScraper:
        return TexasPositionalPdfScraper(
            county_name="Dallas",
            source_url="https://www.dallascounty.org/government/district-clerk/quick-links.php",
            state="TX",
            config=self._CONFIG,
        )

    def _leads(self):
        if not self._FIXTURE.exists():
            pytest.skip("fixture missing — run generate_tx_fixtures.py")
        return self._make_scraper().parse(self._FIXTURE.read_bytes())

    def test_parse_leads_count(self):
        """Fixture PDF has 2 data rows."""
        assert len(self._leads()) == 2

    def test_case_numbers(self):
        """Both case numbers must be extracted from the fixture."""
        leads = self._leads()
        cases = [lead.case_number for lead in leads]
        assert "TX-18-01345" in cases
        assert "TX-20-00762" in cases

    def test_surplus_amount_spaced_tokens(self):
        """Split-token amount '$ 2 6,440.02' must reassemble to Decimal('26440.02')."""
        leads = self._leads()
        first = next(lead for lead in leads if lead.case_number == "TX-18-01345")
        assert first.surplus_amount == Decimal("26440.02")

    def test_surplus_amount_second_row(self):
        """Split-token amount '$ 4 6,894.56' must reassemble to Decimal('46894.56')."""
        leads = self._leads()
        second = next(lead for lead in leads if lead.case_number == "TX-20-00762")
        assert second.surplus_amount == Decimal("46894.56")

    def test_owner_name_extracted(self):
        """Style text between case number and SHERIFF keyword becomes owner_name."""
        leads = self._leads()
        first = next(lead for lead in leads if lead.case_number == "TX-18-01345")
        assert first.owner_name == "DALLAS COUNTY et al vs WILLIAM J JACKSON"

    def test_property_state_is_tx(self):
        """All Dallas leads must have property_state='TX'."""
        for lead in self._leads():
            assert lead.property_state == "TX"

    def test_sale_type_is_tax_deed(self):
        """sale_type must be 'tax_deed' for all Dallas leads."""
        for lead in self._leads():
            assert lead.sale_type == "tax_deed"


# ─── Fort Bend County — PdfScraper (table mode) ───────────────────────────────


class TestFortBendFixture:
    """Fort Bend County: 7-column Odyssey-style table PDF."""

    _FIXTURE = FIXTURES / "texas_fort_bend_excess_proceeds.pdf"

    _CONFIG = {
        "columns": {
            "case_number": 1,
            "owner_name": 2,
            "surplus_amount": 3,
            "property_address": None,
        },
        "skip_rows_containing": ["Orig Receipt Date", "Case Number"],
    }

    def _make_scraper(self) -> PdfScraper:
        return PdfScraper(
            county_name="Fort Bend",
            source_url="https://odysseyreport.fortbendcountytx.gov/District_Clerk/ExcessProceedsFromTaxSale.pdf",
            state="TX",
            config=self._CONFIG,
        )

    def _leads(self):
        if not self._FIXTURE.exists():
            pytest.skip("fixture missing — run generate_tx_fixtures.py")
        return self._make_scraper().parse(self._FIXTURE.read_bytes())

    def test_parse_leads_count(self):
        """Fixture PDF has 2 data rows (header row must be skipped)."""
        assert len(self._leads()) == 2

    def test_case_numbers(self):
        """col 1 (Case Number) must become case_number for both rows."""
        leads = self._leads()
        cases = [lead.case_number for lead in leads]
        assert "11-DCV-192585" in cases
        assert "07-DCV-156513" in cases

    def test_surplus_amounts(self):
        """col 3 (Ending Balance) must parse correctly for both rows."""
        leads = self._leads()
        first = next(lead for lead in leads if lead.case_number == "11-DCV-192585")
        second = next(lead for lead in leads if lead.case_number == "07-DCV-156513")
        assert first.surplus_amount == Decimal("14223.86")
        assert second.surplus_amount == Decimal("388.54")

    def test_owner_name(self):
        """col 2 (Style) must become owner_name."""
        leads = self._leads()
        first = next(lead for lead in leads if lead.case_number == "11-DCV-192585")
        assert first.owner_name == "Fort Bend County vs Dora Sanders ET AL"

    def test_header_row_excluded(self):
        """The 'Orig Receipt Date' / 'Case Number' header row must not appear as a lead."""
        leads = self._leads()
        for lead in leads:
            assert "Orig Receipt Date" not in (lead.case_number or "")
            assert "Case Number" not in (lead.case_number or "")


# ─── Denton County — PdfScraper (table mode) ──────────────────────────────────


class TestDentonFixture:
    """Denton County: 4-column table with a 3-row header block."""

    _FIXTURE = FIXTURES / "texas_denton_excess_funds.pdf"

    _CONFIG = {
        "columns": {
            "case_number": 0,
            "owner_name": 1,
            "surplus_amount": 2,
            "property_address": None,
        },
        "skip_rows_containing": [
            "David Trantham",
            "Denton County District Clerk",
            "Cause Number",
            "Excess Fund",
            "Amt Deposit",
        ],
    }

    def _make_scraper(self) -> PdfScraper:
        return PdfScraper(
            county_name="Denton",
            source_url="https://www.dentoncounty.gov/DocumentCenter/View/3044/Excess-Tax-Funds-PDF",
            state="TX",
            config=self._CONFIG,
        )

    def _leads(self):
        if not self._FIXTURE.exists():
            pytest.skip("fixture missing — run generate_tx_fixtures.py")
        return self._make_scraper().parse(self._FIXTURE.read_bytes())

    def test_parse_leads_count(self):
        """Fixture PDF has 2 data rows; all 3 header rows must be skipped."""
        assert len(self._leads()) == 2

    def test_case_numbers(self):
        """col 0 (Cause Number) must become case_number."""
        leads = self._leads()
        cases = [lead.case_number for lead in leads]
        assert "18-9095-362" in cases
        assert "19-1234-100" in cases

    def test_surplus_amounts(self):
        """col 2 (Amt Deposit) must parse $-prefixed amounts correctly."""
        leads = self._leads()
        first = next(lead for lead in leads if lead.case_number == "18-9095-362")
        second = next(lead for lead in leads if lead.case_number == "19-1234-100")
        assert first.surplus_amount == Decimal("60750.20")
        assert second.surplus_amount == Decimal("12500.00")

    def test_owner_name(self):
        """col 1 (Name) must become owner_name."""
        leads = self._leads()
        first = next(lead for lead in leads if lead.case_number == "18-9095-362")
        assert first.owner_name == "Arreola Gabriel Guillermo"

    def test_header_rows_excluded(self):
        """Multi-row header block (clerk name, title, column labels) must be absent."""
        leads = self._leads()
        for lead in leads:
            assert "David Trantham" not in (lead.case_number or "")
            assert "Denton County" not in (lead.case_number or "")
            assert "Cause Number" not in (lead.case_number or "")


# ─── Galveston County — ParentPagePdfScraper (text_line_mode) ─────────────────


class TestGalvestonFixture:
    """Galveston County: text-line PDF, no dollar sign on amounts."""

    _FIXTURE = FIXTURES / "texas_galveston_excess_proceeds.pdf"

    _CONFIG = {
        "pdf_link_selector": "a[href*='showpublisheddocument']",
        "base_url": "https://www.galvestoncountytx.gov",
        "text_line_mode": True,
        "line_pattern": (
            r"^(?P<case>\d{2}-TX-\d{4})\s+"
            r"(?P<owner>.+?)\s+"
            r"Registry Account\s+"
            r"\d{2}/\d{2}/\d{4}\s+"
            r"\d{2}/\d{2}/\d{4}\s+"
            r"(?P<amt>[\d,]+\.?\d*)\s*$"
        ),
        "fields": {
            "case": "case_number",
            "owner": "owner_name",
            "amt": "surplus_amount",
        },
    }

    def _make_scraper(self) -> ParentPagePdfScraper:
        return ParentPagePdfScraper(
            county_name="Galveston",
            source_url=(
                "https://www.galvestoncountytx.gov"
                "/our-county/district-clerk/excess-proceeds"
            ),
            state="TX",
            config=self._CONFIG,
        )

    def _leads(self):
        if not self._FIXTURE.exists():
            pytest.skip("fixture missing — run generate_tx_fixtures.py")
        return self._make_scraper().parse(self._FIXTURE.read_bytes())

    def test_parse_leads_count(self):
        """Fixture PDF has 2 data rows; column header must be skipped."""
        assert len(self._leads()) == 2

    def test_case_numbers(self):
        """YY-TX-NNNN formatted case numbers must be extracted."""
        leads = self._leads()
        cases = [lead.case_number for lead in leads]
        assert "15-TX-0451" in cases
        assert "23-TX-0532" in cases

    def test_surplus_amounts_no_dollar_sign(self):
        """Amounts have no dollar sign prefix; must still parse correctly."""
        leads = self._leads()
        first = next(lead for lead in leads if lead.case_number == "15-TX-0451")
        second = next(lead for lead in leads if lead.case_number == "23-TX-0532")
        assert first.surplus_amount == Decimal("5842.82")
        assert second.surplus_amount == Decimal("28197.23")

    def test_owner_name(self):
        """Text between case number and 'Registry Account' becomes owner_name."""
        leads = self._leads()
        first = next(lead for lead in leads if lead.case_number == "15-TX-0451")
        assert first.owner_name == "Wilson Smith"

    def test_header_line_excluded(self):
        """The column header line must not produce a lead."""
        leads = self._leads()
        for lead in leads:
            assert "Case Number" not in lead.case_number


# ─── Young County — ParentPagePdfScraper (table mode) ─────────────────────────


class TestYoungFixture:
    """Young County: 3-column table, no owner name, no dollar sign on amounts."""

    _FIXTURE = FIXTURES / "texas_young_excess_proceeds.pdf"

    _CONFIG = {
        "pdf_link_pattern": "excess_proceeds",
        "base_url": "https://www.co.young.tx.us",
        "columns": {
            "case_number": 0,
            "owner_name": 99,
            "surplus_amount": 2,
            "property_address": None,
        },
        "skip_rows_containing": ["Cause Number", "Date Deposited", "Amount Held"],
    }

    def _make_scraper(self) -> ParentPagePdfScraper:
        return ParentPagePdfScraper(
            county_name="Young",
            source_url="https://www.co.young.tx.us/page/young.District.Clerk",
            state="TX",
            config=self._CONFIG,
        )

    def _leads(self):
        if not self._FIXTURE.exists():
            pytest.skip("fixture missing — run generate_tx_fixtures.py")
        return self._make_scraper().parse(self._FIXTURE.read_bytes())

    def test_parse_leads_count(self):
        """Fixture PDF has 2 data rows; header must be skipped."""
        assert len(self._leads()) == 2

    def test_case_numbers(self):
        """col 0 (Cause Number) must become case_number."""
        leads = self._leads()
        cases = [lead.case_number for lead in leads]
        assert "T04911" in cases
        assert "T05345" in cases

    def test_surplus_amounts_no_dollar_sign(self):
        """Amounts have no dollar sign prefix; comma-separated values must parse."""
        leads = self._leads()
        first = next(lead for lead in leads if lead.case_number == "T04911")
        second = next(lead for lead in leads if lead.case_number == "T05345")
        assert first.surplus_amount == Decimal("5469.86")
        assert second.surplus_amount == Decimal("1986.30")

    def test_owner_name_is_none(self):
        """col 99 is out-of-range so owner_name must be None for all rows."""
        for lead in self._leads():
            assert lead.owner_name is None

    def test_header_row_excluded(self):
        """'Cause Number' header row must not produce a lead."""
        leads = self._leads()
        for lead in leads:
            assert "Cause Number" not in lead.case_number


# ─── Houston County (TX) — ParentPagePdfScraper (table mode) ──────────────────


class TestHoustonTxFixture:
    """Houston County TX (seat: Crockett): 4-column table, no owner name."""

    _FIXTURE = FIXTURES / "texas_houston_excess_funds.pdf"

    _CONFIG = {
        "pdf_link_pattern": "Excess",
        "base_url": "https://www.co.houston.tx.us",
        "columns": {
            "case_number": 2,
            "owner_name": 99,
            "surplus_amount": 1,
            "property_address": None,
        },
        "skip_rows_containing": [
            "DATE RECEIPTED",
            "AMOUNT OF EXCESS",
            "IN REGISTRY",
            "CAUSE NUMBER",
        ],
    }

    def _make_scraper(self) -> ParentPagePdfScraper:
        return ParentPagePdfScraper(
            county_name="Houston",
            source_url="https://www.co.houston.tx.us/page/houston.District.Clerk",
            state="TX",
            config=self._CONFIG,
        )

    def _leads(self):
        if not self._FIXTURE.exists():
            pytest.skip("fixture missing — run generate_tx_fixtures.py")
        return self._make_scraper().parse(self._FIXTURE.read_bytes())

    def test_parse_leads_count(self):
        """Fixture PDF has 2 data rows; header row must be skipped."""
        assert len(self._leads()) == 2

    def test_case_numbers(self):
        """col 2 (Cause Number) must become case_number."""
        leads = self._leads()
        cases = [lead.case_number for lead in leads]
        assert "21-0188" in cases
        assert "20-1044" in cases

    def test_surplus_amounts(self):
        """col 1 (Amount) with $-prefix must parse correctly."""
        leads = self._leads()
        first = next(lead for lead in leads if lead.case_number == "21-0188")
        second = next(lead for lead in leads if lead.case_number == "20-1044")
        assert first.surplus_amount == Decimal("95292.90")
        assert second.surplus_amount == Decimal("7804.05")

    def test_owner_name_is_none(self):
        """col 99 is out-of-range so owner_name must be None for all rows."""
        for lead in self._leads():
            assert lead.owner_name is None

    def test_header_row_excluded(self):
        """'DATE RECEIPTED' / 'CAUSE NUMBER' header row must not produce a lead."""
        leads = self._leads()
        for lead in leads:
            assert "DATE RECEIPTED" not in lead.case_number
            assert "CAUSE NUMBER" not in lead.case_number
