"""Fixture-based tests for GeorgiaExcessFundsPdfScraper.

These tests load real PDF bytes generated by tests/fixtures/generate_ga_fixtures.py
and call scraper.parse(bytes) directly.  No pdfplumber mocking is used — the full
parsing pipeline (pdfplumber table extraction → per-county row parser) runs end-to-end.

Regenerate fixtures:
    python tests/fixtures/generate_ga_fixtures.py
"""

from __future__ import annotations

from decimal import Decimal
from pathlib import Path

import pytest

from app.ingestion.georgia_pdf_scraper import GeorgiaExcessFundsPdfScraper

FIXTURES = Path(__file__).parent.parent / "fixtures"


def _load_fixture(filename: str) -> bytes:
    path = FIXTURES / filename
    if not path.exists():
        pytest.skip(f"Fixture not found: {path}  — run generate_ga_fixtures.py")
    return path.read_bytes()


def _make_scraper(county: str, layout: str) -> GeorgiaExcessFundsPdfScraper:
    return GeorgiaExcessFundsPdfScraper(
        county_name=county,
        source_url="https://example.com",
        state="GA",
        config={"layout": layout},
    )


# ─── Gwinnett ─────────────────────────────────────────────────────────────────


class TestGwinnettFixture:
    """Gwinnett layout: col2=case_number, col3=owner, col4=addr, col5=amount, col6=date."""

    @pytest.fixture(scope="class")
    def leads(self):
        scraper = _make_scraper("Gwinnett", "gwinnett")
        return scraper.parse(_load_fixture("georgia_gwinnett_excess_funds.pdf"))

    def test_parse_leads_count(self, leads):
        # Header row is skipped (col2 == "PARCEL NUMBER"); 2 data rows remain.
        assert len(leads) == 2

    def test_case_numbers(self, leads):
        assert leads[0].case_number == "R5018 019A"
        assert leads[1].case_number == "R1234 567B"

    def test_surplus_amounts(self, leads):
        assert leads[0].surplus_amount == Decimal("3789.69")
        assert leads[1].surplus_amount == Decimal("12500.00")

    def test_owner_names(self, leads):
        assert leads[0].owner_name == "GRAHAM UREL MRS"
        assert leads[1].owner_name == "JONES ROBERT E"

    def test_property_addresses(self, leads):
        assert leads[0].property_address == "187 HUFF DR DULUTH GA"
        assert leads[1].property_address == "456 OAK AVE LAWRENCEVILLE GA"

    def test_sale_dates(self, leads):
        assert leads[0].sale_date == "May 2021"
        assert leads[1].sale_date == "Sep 2022"

    def test_property_state_is_ga(self, leads):
        for lead in leads:
            assert lead.property_state == "GA"

    def test_sale_type_is_tax_deed(self, leads):
        for lead in leads:
            assert lead.sale_type == "tax_deed"


# ─── DeKalb ───────────────────────────────────────────────────────────────────


class TestDeKalbFixture:
    """DeKalb layout: col0=case_number, col3=amount, col6=date, cols7-9=owner, col10=addr, col11=city, col12=zip."""

    @pytest.fixture(scope="class")
    def leads(self):
        scraper = _make_scraper("DeKalb", "dekalb")
        return scraper.parse(_load_fixture("georgia_dekalb_excess_funds.pdf"))

    def test_parse_leads_count(self, leads):
        # Header row skipped (col0 == "PARCEL ID"); 2 data rows remain.
        assert len(leads) == 2

    def test_case_numbers(self, leads):
        assert leads[0].case_number == "15-001-02-003"
        assert leads[1].case_number == "16-002-03-004"

    def test_surplus_amounts(self, leads):
        assert leads[0].surplus_amount == Decimal("45320.00")
        assert leads[1].surplus_amount == Decimal("8750.50")

    def test_owner_name_joined_from_three_columns(self, leads):
        # cols 7-9 = "JOHNSON", "ROBERT", "W" → joined to "JOHNSON ROBERT W"
        assert leads[0].owner_name == "JOHNSON ROBERT W"

    def test_owner_name_joined_from_two_columns_blank_suffix(self, leads):
        # cols 7-9 = "WILLIAMS", "SARAH", "" → joined to "WILLIAMS SARAH" (blank col9 dropped)
        assert leads[1].owner_name == "WILLIAMS SARAH"

    def test_property_addresses(self, leads):
        assert leads[0].property_address == "789 ELM ST"
        assert leads[1].property_address == "321 PINE RD"

    def test_property_cities(self, leads):
        assert leads[0].property_city == "DECATUR"
        assert leads[1].property_city == "STONE MOUNTAIN"

    def test_property_zips(self, leads):
        assert leads[0].property_zip == "30030"
        assert leads[1].property_zip == "30083"

    def test_sale_dates(self, leads):
        assert leads[0].sale_date == "03/15/2022"
        assert leads[1].sale_date == "07/22/2021"

    def test_property_state_is_ga(self, leads):
        for lead in leads:
            assert lead.property_state == "GA"


# ─── Clayton ──────────────────────────────────────────────────────────────────


class TestClaytonFixture:
    """Clayton layout: col0=owner, col1=case_number, col2=amount, col3=date."""

    @pytest.fixture(scope="class")
    def leads(self):
        scraper = _make_scraper("Clayton", "clayton")
        return scraper.parse(_load_fixture("georgia_clayton_excess_funds.pdf"))

    def test_parse_leads_count(self, leads):
        # Header row has blank col1 → skipped; 2 data rows remain.
        assert len(leads) == 2

    def test_case_numbers(self, leads):
        assert leads[0].case_number == "16-0003498"
        assert leads[1].case_number == "19-0007812"

    def test_surplus_amounts(self, leads):
        assert leads[0].surplus_amount == Decimal("5412.87")
        assert leads[1].surplus_amount == Decimal("22100.00")

    def test_owner_names(self, leads):
        assert leads[0].owner_name == "THOMPSON ALICE B"
        assert leads[1].owner_name == "MARTINEZ CARLOS"

    def test_sale_dates(self, leads):
        assert leads[0].sale_date == "08/01/2023"
        assert leads[1].sale_date == "11/15/2022"

    def test_property_state_is_ga(self, leads):
        for lead in leads:
            assert lead.property_state == "GA"


# ─── Henry ────────────────────────────────────────────────────────────────────


class TestHenryFixture:
    """Henry layout: col0=case_number, col1=owner, col2=addr, col3=date, col4=amount.

    Key edge case: amounts with embedded OCR spaces like "$ 3 85.05" must parse
    to Decimal("385.05").  The Georgia-specific _parse_amount normalizes these
    before calling the parent PdfScraper._parse_amount.
    """

    @pytest.fixture(scope="class")
    def leads(self):
        scraper = _make_scraper("Henry", "henry")
        return scraper.parse(_load_fixture("georgia_henry_excess_funds.pdf"))

    def test_parse_leads_count(self, leads):
        # Header row skipped (col0 == "PARCEL ID"); 2 data rows remain.
        assert len(leads) == 2

    def test_case_numbers(self, leads):
        assert leads[0].case_number == "123-456-789"
        assert leads[1].case_number == "987-654-321"

    def test_normal_surplus_amount(self, leads):
        assert leads[0].surplus_amount == Decimal("9950.00")

    def test_spaced_amount_normalization(self, leads):
        # Fixture col4 = "$ 3 85.05".  After _cell: "$ 3 85.05".
        # After re.sub(r"(?<=\d)\s+(?=\d)", "", ...): "$ 385.05".
        # PdfScraper._parse_amount then yields Decimal("385.05").
        assert leads[1].surplus_amount == Decimal("385.05")

    def test_owner_names(self, leads):
        assert leads[0].owner_name == "DAVIS MARY L"
        assert leads[1].owner_name == "CLARK JAMES T"

    def test_property_addresses(self, leads):
        assert leads[0].property_address == "55 CEDAR LN MCDONOUGH GA"
        assert leads[1].property_address == "10 WALNUT WAY STOCKBRIDGE GA"

    def test_sale_dates(self, leads):
        assert leads[0].sale_date == "05/06/2021"
        assert leads[1].sale_date == "09/18/2020"

    def test_property_state_is_ga(self, leads):
        for lead in leads:
            assert lead.property_state == "GA"


# ─── Hall ─────────────────────────────────────────────────────────────────────


class TestHallFixture:
    """Hall layout: col0=sale_date, col2=case_number, col3=owner, col4=addr, col5=city, col6=amount."""

    @pytest.fixture(scope="class")
    def leads(self):
        scraper = _make_scraper("Hall", "hall")
        return scraper.parse(_load_fixture("georgia_hall_excess_funds.pdf"))

    def test_parse_leads_count(self, leads):
        # Header row skipped (col2 == "MAPCODE"); 2 data rows remain.
        assert len(leads) == 2

    def test_case_numbers(self, leads):
        assert leads[0].case_number == "08-023-004-001"
        assert leads[1].case_number == "12-045-001-002"

    def test_surplus_amounts(self, leads):
        assert leads[0].surplus_amount == Decimal("6300.75")
        assert leads[1].surplus_amount == Decimal("3150.00")

    def test_owner_names(self, leads):
        assert leads[0].owner_name == "NGUYEN PETER"
        assert leads[1].owner_name == "PATEL ANITA K"

    def test_property_addresses(self, leads):
        assert leads[0].property_address == "100 LAKEVIEW DR"
        assert leads[1].property_address == "200 RIVERSIDE RD"

    def test_property_cities(self, leads):
        assert leads[0].property_city == "GAINESVILLE"
        assert leads[1].property_city == "HALL COUNTY"

    def test_sale_dates(self, leads):
        assert leads[0].sale_date == "01/22/2026"
        assert leads[1].sale_date == "03/14/2025"

    def test_property_state_is_ga(self, leads):
        for lead in leads:
            assert lead.property_state == "GA"


# ─── Cross-layout edge cases ──────────────────────────────────────────────────


class TestGeorgiaScraperEdgeCases:
    """Behavioral edge cases that apply across all layouts."""

    def test_unsupported_layout_raises_runtime_error(self):
        scraper = _make_scraper("Unknown", "nonexistent_layout")
        with pytest.raises(RuntimeError, match="unsupported Georgia PDF layout"):
            scraper.parse(b"%PDF-1.4 fake")

    def test_gwinnett_skips_highlighted_parcels_row(self):
        """Rows where col1 contains 'Highlighted parcels' must be skipped."""
        import io

        from reportlab.lib.pagesizes import letter
        from reportlab.lib.units import inch
        from reportlab.platypus import SimpleDocTemplate, Table, TableStyle

        rows = [
            ["#", "NAME", "PARCEL NUMBER", "OWNER", "SITUS", "EXCESS", "DATE"],
            ["", "Highlighted parcels are pending", "H9999 999Z", "SKIP ME", "123 SKIP RD", "$1.00", "Jan 2020"],
            ["1", "BUYER A", "R0001 001A", "VALID OWNER", "1 VALID ST", "$500.00", "Feb 2021"],
        ]
        buf = io.BytesIO()
        doc = SimpleDocTemplate(buf, pagesize=letter, leftMargin=0.25 * inch, rightMargin=0.25 * inch, topMargin=0.5 * inch, bottomMargin=0.5 * inch)
        table = Table(rows)
        table.setStyle(TableStyle([("GRID", (0, 0), (-1, -1), 0.5, (0, 0, 0)), ("FONTNAME", (0, 0), (-1, -1), "Courier"), ("FONTSIZE", (0, 0), (-1, -1), 7)]))
        doc.build([table])
        pdf_bytes = buf.getvalue()

        scraper = _make_scraper("Gwinnett", "gwinnett")
        leads = scraper.parse(pdf_bytes)

        assert len(leads) == 1
        assert leads[0].case_number == "R0001 001A"

    def test_henry_skips_redeemed_rows(self):
        """Henry rows where col4 contains 'REDEEMED' must be skipped."""
        import io

        from reportlab.lib.pagesizes import letter
        from reportlab.lib.units import inch
        from reportlab.platypus import SimpleDocTemplate, Table, TableStyle

        rows = [
            ["PARCEL ID", "OWNER NAME", "PROPERTY ADDRESS", "SALE DATE", "EXCESS AMOUNT"],
            ["AAA-111-222", "SKIP OWNER", "1 SKIP ST", "01/01/2020", "REDEEMED"],
            ["BBB-333-444", "VALID OWNER", "2 VALID AVE", "02/02/2021", "$750.00"],
        ]
        buf = io.BytesIO()
        doc = SimpleDocTemplate(buf, pagesize=letter, leftMargin=0.25 * inch, rightMargin=0.25 * inch, topMargin=0.5 * inch, bottomMargin=0.5 * inch)
        table = Table(rows)
        table.setStyle(TableStyle([("GRID", (0, 0), (-1, -1), 0.5, (0, 0, 0)), ("FONTNAME", (0, 0), (-1, -1), "Courier"), ("FONTSIZE", (0, 0), (-1, -1), 7)]))
        doc.build([table])
        pdf_bytes = buf.getvalue()

        scraper = _make_scraper("Henry", "henry")
        leads = scraper.parse(pdf_bytes)

        assert len(leads) == 1
        assert leads[0].case_number == "BBB-333-444"

    def test_henry_skips_no_proceeds_rows(self):
        """Henry rows where col4 contains 'NO PROCEEDS' must be skipped."""
        import io

        from reportlab.lib.pagesizes import letter
        from reportlab.lib.units import inch
        from reportlab.platypus import SimpleDocTemplate, Table, TableStyle

        rows = [
            ["PARCEL ID", "OWNER NAME", "PROPERTY ADDRESS", "SALE DATE", "EXCESS AMOUNT"],
            ["CCC-555-666", "SKIP OWNER", "3 SKIP BLVD", "03/03/2020", "NO PROCEEDS"],
            ["DDD-777-888", "VALID OWNER", "4 VALID ST", "04/04/2022", "$1,200.00"],
        ]
        buf = io.BytesIO()
        doc = SimpleDocTemplate(buf, pagesize=letter, leftMargin=0.25 * inch, rightMargin=0.25 * inch, topMargin=0.5 * inch, bottomMargin=0.5 * inch)
        table = Table(rows)
        table.setStyle(TableStyle([("GRID", (0, 0), (-1, -1), 0.5, (0, 0, 0)), ("FONTNAME", (0, 0), (-1, -1), "Courier"), ("FONTSIZE", (0, 0), (-1, -1), 7)]))
        doc.build([table])
        pdf_bytes = buf.getvalue()

        scraper = _make_scraper("Henry", "henry")
        leads = scraper.parse(pdf_bytes)

        assert len(leads) == 1
        assert leads[0].case_number == "DDD-777-888"

    def test_clayton_skips_total_excess_funds_row(self):
        """Clayton rows where 'TOTAL EXCESS FUNDS' appears in col0 must be skipped."""
        import io

        from reportlab.lib.pagesizes import letter
        from reportlab.lib.units import inch
        from reportlab.platypus import SimpleDocTemplate, Table, TableStyle

        rows = [
            ["OWNER NAME", "CASE #", "AMOUNT", "DATE"],
            ["VALID OWNER", "22-0001111", "$3,000.00", "01/15/2023"],
            ["TOTAL EXCESS FUNDS", "99-9999999", "$999,999.99", "N/A"],
        ]
        buf = io.BytesIO()
        doc = SimpleDocTemplate(buf, pagesize=letter, leftMargin=0.25 * inch, rightMargin=0.25 * inch, topMargin=0.5 * inch, bottomMargin=0.5 * inch)
        table = Table(rows)
        table.setStyle(TableStyle([("GRID", (0, 0), (-1, -1), 0.5, (0, 0, 0)), ("FONTNAME", (0, 0), (-1, -1), "Courier"), ("FONTSIZE", (0, 0), (-1, -1), 7)]))
        doc.build([table])
        pdf_bytes = buf.getvalue()

        scraper = _make_scraper("Clayton", "clayton")
        leads = scraper.parse(pdf_bytes)

        assert len(leads) == 1
        assert leads[0].case_number == "22-0001111"

    def test_deduplication_removes_duplicate_rows(self):
        """Duplicate rows with the same case_number + amount must produce only one lead."""
        import io

        from reportlab.lib.pagesizes import letter
        from reportlab.lib.units import inch
        from reportlab.platypus import SimpleDocTemplate, Table, TableStyle

        rows = [
            ["OWNER NAME", "CASE #", "AMOUNT", "DATE"],
            ["SMITH JOHN", "DUP-001", "$2,500.00", "05/01/2022"],
            ["SMITH JOHN", "DUP-001", "$2,500.00", "05/01/2022"],  # exact duplicate
        ]
        buf = io.BytesIO()
        doc = SimpleDocTemplate(buf, pagesize=letter, leftMargin=0.25 * inch, rightMargin=0.25 * inch, topMargin=0.5 * inch, bottomMargin=0.5 * inch)
        table = Table(rows)
        table.setStyle(TableStyle([("GRID", (0, 0), (-1, -1), 0.5, (0, 0, 0)), ("FONTNAME", (0, 0), (-1, -1), "Courier"), ("FONTSIZE", (0, 0), (-1, -1), 7)]))
        doc.build([table])
        pdf_bytes = buf.getvalue()

        scraper = _make_scraper("Clayton", "clayton")
        leads = scraper.parse(pdf_bytes)

        assert len(leads) == 1
        assert leads[0].case_number == "DUP-001"
