"""Fixture-based tests for California county PDF scrapers.

These tests load real PDF bytes generated by generate_ca_fixtures.py and call
scraper.parse(bytes) directly — no pdfplumber mocking. This exercises real PDF
parsing in addition to the parser logic.

Run the fixture generator once if the fixture files are absent:

    source .venv/bin/activate
    python tests/fixtures/generate_ca_fixtures.py
"""

from __future__ import annotations

from decimal import Decimal
from pathlib import Path

import pytest

from app.ingestion.california_pdf_scraper import (
    CaliforniaExcessProceedsScraper,
    SanDiegoFinalReportScraper,
)

FIXTURES_DIR = Path(__file__).parent.parent / "fixtures"

# ---------------------------------------------------------------------------
# County configs — copied verbatim from the activation migration
# ---------------------------------------------------------------------------

_LA_CONFIG = {
    "line_pattern": (
        r"^(?P<parcel>\d{4}-\d{3}-\d{3})\s+"
        r"(?P<case>\d{4})\s+"
        r"\$(?P<sale>[\d,]+\.\d{2})\s+"
        r"(?:X\s+)?\$(?P<amt>[\d,]+\.\d{2})$"
    ),
    "fields": {
        "case": "case_number",
        "parcel": "parcel_id",
        "amt": "surplus_amount",
    },
}

_ORANGE_CONFIG = {
    "line_pattern": (
        r"^(?P<case>\d+)\s+"
        r"(?P<parcel>\d{3}-\d{3}-\d{2})\s+"
        r"(?P<tax_default>\d{2}-\d{6})\s+"
        r"(?P<property_type>[A-Z-]+)\s+"
        r"(?P<body>.+?)\s+"
        r"\$(?P<minimum>[\d,]+\.\d{2})\s+"
        r"\$(?P<sale>[\d,]+\.\d{2})\s+"
        r"\$(?P<amt>[\d,]+\.\d{2})\s+"
        r"(?P<date>\d{2}/\d{2}/\d{2})$"
    ),
    "fields": {
        "case": "case_number",
        "parcel": "parcel_id",
        "amt": "surplus_amount",
        "date": "sale_date",
    },
    "body_group": "body",
    "body_split_pattern": r"(?P<owner>.+?)\s+(?P<address>(?:SITUS|NO SITUS).+)$",
}

_SACRAMENTO_CONFIG = {
    "line_pattern": (
        r"^(?P<parcel>\d{3}-\d{4}-\d{3}-\d{4})\s+\$\s*(?P<amt>[\d,]+\.\d{2})$"
    ),
    "fields": {
        "parcel": "parcel_id",
        "amt": "surplus_amount",
    },
    "case_group": "parcel",
}

_FRESNO_CONFIG = {
    "line_pattern": (
        r"^(?P<case>\d+)\s+(?P<parcel>[0-9A-Z-]+)\s+"
        r"(?P<sale>[\d,]+\.\d{2})\s+(?P<amt>[\d,]+\.\d{2})$"
    ),
    "fields": {
        "case": "case_number",
        "parcel": "parcel_id",
        "amt": "surplus_amount",
    },
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _load_fixture(filename: str) -> bytes:
    path = FIXTURES_DIR / filename
    if not path.exists():
        pytest.skip(
            f"Fixture not found: {path}. "
            "Run: python tests/fixtures/generate_ca_fixtures.py"
        )
    return path.read_bytes()


# ---------------------------------------------------------------------------
# Los Angeles
# ---------------------------------------------------------------------------

class TestLosAngelesFixture:
    """CaliforniaExcessProceedsScraper with LA configuration."""

    @pytest.fixture(scope="class")
    def leads(self):
        scraper = CaliforniaExcessProceedsScraper(
            county_name="Los Angeles",
            state="CA",
            source_url="https://ttc.lacounty.gov/auction-contact-us/",
            config=_LA_CONFIG,
        )
        return scraper.parse(_load_fixture("california_la_excess_proceeds.pdf"))

    def test_minimum_lead_count(self, leads):
        assert len(leads) >= 2

    def test_zero_amount_rows_are_excluded(self, leads):
        # The fixture has a row with X flag and $0.00 — must be filtered
        assert all(lead.surplus_amount > 0 for lead in leads)

    def test_first_lead_case_number(self, leads):
        assert leads[0].case_number == "3063"

    def test_first_lead_parcel_id(self, leads):
        assert leads[0].parcel_id == "2061-025-010"

    def test_first_lead_surplus_amount(self, leads):
        assert leads[0].surplus_amount == Decimal("36307.59")

    def test_second_lead_case_number(self, leads):
        assert leads[1].case_number == "3192"

    def test_second_lead_surplus_amount(self, leads):
        assert leads[1].surplus_amount == Decimal("9482.11")

    def test_property_state_is_ca(self, leads):
        assert all(lead.property_state == "CA" for lead in leads)

    def test_sale_type_is_tax_deed(self, leads):
        assert all(lead.sale_type == "tax_deed" for lead in leads)


# ---------------------------------------------------------------------------
# San Diego
# ---------------------------------------------------------------------------

class TestSanDiegoFixture:
    """SanDiegoFinalReportScraper with real PDF bytes."""

    @pytest.fixture(scope="class")
    def leads(self):
        scraper = SanDiegoFinalReportScraper(
            county_name="San Diego",
            state="CA",
            source_url=(
                "https://www.sdttc.com/content/ttc/en/tax-collection/"
                "property-tax-sales/prior-sales-results.html"
            ),
            config={},
        )
        return scraper.parse(_load_fixture("california_san_diego_final_report.pdf"))

    def test_minimum_lead_count(self, leads):
        # Fixture has 2 SOLD records and 1 REDEEMED record
        assert len(leads) >= 2

    def test_redeemed_row_is_excluded(self, leads):
        case_numbers = {lead.case_number for lead in leads}
        assert "0066" not in case_numbers

    def test_first_lead_case_number(self, leads):
        assert leads[0].case_number == "0062"

    def test_first_lead_parcel_id(self, leads):
        assert leads[0].parcel_id == "132-190-04-00"

    def test_first_lead_owner_name(self, leads):
        assert leads[0].owner_name == "ELDRIDGE PRISCILLA F"

    def test_first_lead_surplus_amount(self, leads):
        assert leads[0].surplus_amount == Decimal("1589.51")

    def test_first_lead_sale_date_iso_format(self, leads):
        assert leads[0].sale_date == "2025-04-24"

    def test_second_lead_case_number(self, leads):
        assert leads[1].case_number == "0073"

    def test_second_lead_parcel_id(self, leads):
        assert leads[1].parcel_id == "141-381-43-00"

    def test_second_lead_surplus_amount(self, leads):
        assert leads[1].surplus_amount == Decimal("812.47")

    def test_property_state_is_ca(self, leads):
        assert all(lead.property_state == "CA" for lead in leads)


# ---------------------------------------------------------------------------
# Orange
# ---------------------------------------------------------------------------

class TestOrangeFixture:
    """CaliforniaExcessProceedsScraper with Orange configuration."""

    @pytest.fixture(scope="class")
    def leads(self):
        scraper = CaliforniaExcessProceedsScraper(
            county_name="Orange",
            state="CA",
            source_url="https://www.octreasurer.gov/taxauction",
            config=_ORANGE_CONFIG,
        )
        return scraper.parse(_load_fixture("california_orange_excess_proceeds.pdf"))

    def test_minimum_lead_count(self, leads):
        # Fixture has 1 non-zero row (second row has $0.00 surplus)
        assert len(leads) >= 1

    def test_zero_amount_rows_are_excluded(self, leads):
        assert all(lead.surplus_amount > 0 for lead in leads)

    def test_first_lead_case_number(self, leads):
        assert leads[0].case_number == "026"

    def test_first_lead_parcel_id(self, leads):
        assert leads[0].parcel_id == "105-101-10"

    def test_first_lead_surplus_amount(self, leads):
        assert leads[0].surplus_amount == Decimal("37429.25")

    def test_first_lead_sale_date_iso_format(self, leads):
        assert leads[0].sale_date == "2025-07-08"

    def test_first_lead_owner_name_extracted_from_body(self, leads):
        assert leads[0].owner_name == "BAKER, RONALD HOWARD"

    def test_first_lead_property_address_extracted_from_body(self, leads):
        assert leads[0].property_address == "SITUS NA, SILVERADO"

    def test_property_state_is_ca(self, leads):
        assert all(lead.property_state == "CA" for lead in leads)


# ---------------------------------------------------------------------------
# Sacramento
# ---------------------------------------------------------------------------

class TestSacramentoFixture:
    """CaliforniaExcessProceedsScraper with Sacramento configuration."""

    @pytest.fixture(scope="class")
    def leads(self):
        scraper = CaliforniaExcessProceedsScraper(
            county_name="Sacramento",
            state="CA",
            source_url="https://finance.saccounty.gov/Tax/Pages/TaxSale.aspx",
            config=_SACRAMENTO_CONFIG,
        )
        return scraper.parse(_load_fixture("california_sacramento_excess_proceeds.pdf"))

    def test_minimum_lead_count(self, leads):
        assert len(leads) >= 2

    def test_non_matching_rows_are_excluded(self, leads):
        # 'REDEEMED' row and header rows should not appear
        case_numbers = {lead.case_number for lead in leads}
        assert "022-0203-008-0000" not in case_numbers

    def test_first_lead_case_number_equals_parcel(self, leads):
        # Sacramento uses parcel as case_number via case_group
        assert leads[0].case_number == "065-0051-019-0000"
        assert leads[0].parcel_id == "065-0051-019-0000"

    def test_first_lead_surplus_amount(self, leads):
        assert leads[0].surplus_amount == Decimal("363924.04")

    def test_second_lead_case_number(self, leads):
        assert leads[1].case_number == "074-0102-001-0000"

    def test_second_lead_surplus_amount(self, leads):
        assert leads[1].surplus_amount == Decimal("14550.50")

    def test_property_state_is_ca(self, leads):
        assert all(lead.property_state == "CA" for lead in leads)


# ---------------------------------------------------------------------------
# Fresno
# ---------------------------------------------------------------------------

class TestFresnoFixture:
    """CaliforniaExcessProceedsScraper with Fresno configuration."""

    @pytest.fixture(scope="class")
    def leads(self):
        scraper = CaliforniaExcessProceedsScraper(
            county_name="Fresno",
            state="CA",
            source_url=(
                "https://www.fresnocountyca.gov/Departments/"
                "Auditor-Controller-Treasurer-Tax-Collector/"
                "Property-Tax-Information/Tax-Sale-Excess-Proceeds"
            ),
            config=_FRESNO_CONFIG,
        )
        return scraper.parse(_load_fixture("california_fresno_excess_proceeds.pdf"))

    def test_minimum_lead_count(self, leads):
        assert len(leads) >= 2

    def test_zero_amount_rows_are_excluded(self, leads):
        assert all(lead.surplus_amount > 0 for lead in leads)

    def test_first_lead_case_number(self, leads):
        assert leads[0].case_number == "40"

    def test_first_lead_parcel_id(self, leads):
        assert leads[0].parcel_id == "404-493-04"

    def test_first_lead_surplus_amount(self, leads):
        assert leads[0].surplus_amount == Decimal("253253.00")

    def test_second_lead_case_number(self, leads):
        assert leads[1].case_number == "171"

    def test_second_lead_parcel_id(self, leads):
        assert leads[1].parcel_id == "088-220-15"

    def test_second_lead_surplus_amount(self, leads):
        assert leads[1].surplus_amount == Decimal("292.13")

    def test_property_state_is_ca(self, leads):
        assert all(lead.property_state == "CA" for lead in leads)

    def test_sale_type_is_tax_deed(self, leads):
        assert all(lead.sale_type == "tax_deed" for lead in leads)
