"""Fixture-based tests for Ohio county excess proceeds scrapers.

These tests load real bytes from pre-generated fixture files and call
scraper.parse(bytes) directly — no mocking of pdfplumber or openpyxl.

Fixture files are generated by:
    python tests/fixtures/generate_oh_fixtures.py

Ohio counties under test:
- Cuyahoga — XlsxScraper, simple_table_mode (XLSX)
- Lake      — PdfScraper, table mode (3-column PDF)
- Medina    — ParentPagePdfScraper, table mode (4-column PDF)
- Fairfield — ParentPagePdfScraper, table mode (7-column PDF)
- Montgomery — PdfScraper, table mode (5-column PDF)
"""

from __future__ import annotations

from decimal import Decimal
from pathlib import Path

import pytest

FIXTURES_DIR = Path(__file__).parent.parent / "fixtures"


# ─── Fixture loaders ─────────────────────────────────────────────────────────


def _load_fixture(filename: str) -> bytes:
    path = FIXTURES_DIR / filename
    if not path.exists():
        pytest.skip(f"Fixture file missing: {path}. Run tests/fixtures/generate_oh_fixtures.py")
    return path.read_bytes()


# ─── Cuyahoga County — XlsxScraper ───────────────────────────────────────────


class TestCuyahogaXlsxFixture:
    """Cuyahoga County: XlsxScraper against a real XLSX fixture.

    Fixture: ohio_cuyahoga_excess_funds.xlsx
    Column layout (indices):
      0: case_number
      1: parcel_id
      2: property_address
      3: owner_name
      4: Sale Date (not captured)
      5: surplus_amount
    """

    _CONFIG = {
        "simple_table_mode": True,
        "columns": {
            "case_number": 0,
            "parcel_id": 1,
            "property_address": 2,
            "owner_name": 3,
            "surplus_amount": 5,
        },
        "skip_rows_containing": ["Case Number", "Case No", "case number"],
    }

    def _make_scraper(self):
        from app.ingestion.xlsx_scraper import XlsxScraper

        return XlsxScraper(
            county_name="Cuyahoga",
            source_url=(
                "https://cuyahogacms.blob.core.windows.net/home/docs/default-source/"
                "coc/excessfunds-foreclosure.xlsx"
            ),
            state="OH",
            config=self._CONFIG,
        )

    def test_parse_leads_count(self):
        """Fixture has 3 data rows; parse() must return exactly 3 leads."""
        fixture_bytes = _load_fixture("ohio_cuyahoga_excess_funds.xlsx")
        leads = self._make_scraper().parse(fixture_bytes)
        assert len(leads) == 3

    def test_case_numbers(self):
        """All case numbers must be extracted in order."""
        fixture_bytes = _load_fixture("ohio_cuyahoga_excess_funds.xlsx")
        leads = self._make_scraper().parse(fixture_bytes)
        case_numbers = [l.case_number for l in leads]
        assert case_numbers == ["2024-CV-001234", "2024-CV-002345", "2023-CV-009876"]

    def test_surplus_amounts(self):
        """Surplus amounts must be parsed as Decimal from numeric Excel cells."""
        fixture_bytes = _load_fixture("ohio_cuyahoga_excess_funds.xlsx")
        leads = self._make_scraper().parse(fixture_bytes)
        assert leads[0].surplus_amount == Decimal("15432")
        assert leads[1].surplus_amount == Decimal("8750.5")
        assert leads[2].surplus_amount == Decimal("31200")

    def test_parcel_id(self):
        """parcel_id must be extracted from column 1."""
        fixture_bytes = _load_fixture("ohio_cuyahoga_excess_funds.xlsx")
        leads = self._make_scraper().parse(fixture_bytes)
        assert leads[0].parcel_id == "123-45-678"
        assert leads[1].parcel_id == "234-56-789"
        assert leads[2].parcel_id == "345-67-890"

    def test_property_address(self):
        """property_address must be extracted from column 2."""
        fixture_bytes = _load_fixture("ohio_cuyahoga_excess_funds.xlsx")
        leads = self._make_scraper().parse(fixture_bytes)
        assert leads[0].property_address == "100 Main St Cleveland OH 44113"
        assert leads[2].property_address == "300 Oak Ave Parma OH 44129"

    def test_owner_name(self):
        """owner_name must be extracted from column 3."""
        fixture_bytes = _load_fixture("ohio_cuyahoga_excess_funds.xlsx")
        leads = self._make_scraper().parse(fixture_bytes)
        assert leads[0].owner_name == "John Doe"
        assert leads[1].owner_name == "Jane Smith"

    def test_header_row_excluded(self):
        """Header row ('Case Number', ...) must be skipped via skip_rows_containing."""
        fixture_bytes = _load_fixture("ohio_cuyahoga_excess_funds.xlsx")
        leads = self._make_scraper().parse(fixture_bytes)
        case_numbers = [l.case_number for l in leads]
        assert "Case Number" not in case_numbers

    def test_sale_type_is_tax_deed(self):
        """All leads must have sale_type='tax_deed'."""
        fixture_bytes = _load_fixture("ohio_cuyahoga_excess_funds.xlsx")
        leads = self._make_scraper().parse(fixture_bytes)
        for lead in leads:
            assert lead.sale_type == "tax_deed"

    def test_state_is_oh(self):
        """Scraper state must be OH."""
        assert self._make_scraper().state == "OH"


# ─── Lake County — PdfScraper (3-column) ─────────────────────────────────────


class TestLakePdfFixture:
    """Lake County: PdfScraper against a real PDF fixture with a 3-column table.

    Fixture: ohio_lake_excess_funds.pdf
    Column layout:
      0: case_number  (CASE NUMBER)
      1: owner_name   (DEBTOR)
      2: surplus_amount (BALANCE)
    """

    _CONFIG = {
        "columns": {
            "case_number": 0,
            "owner_name": 1,
            "surplus_amount": 2,
            "property_address": None,
        },
        "skip_rows_containing": [
            "CASE NUMBER",
            "Case Number",
            "DEBTOR",
            "BALANCE",
            "Lake County",
        ],
    }

    def _make_scraper(self):
        from app.ingestion.pdf_scraper import PdfScraper

        return PdfScraper(
            county_name="Lake",
            source_url=(
                "https://www.lakecountyohio.gov/coc/wp-content/uploads/sites/58/"
                "2021/06/WEBSITE-LEGAL-NOTICE-4-2-25.pdf"
            ),
            state="OH",
            config=self._CONFIG,
        )

    def test_parse_leads_count(self):
        """Fixture has 2 data rows; parse() must return exactly 2 leads."""
        fixture_bytes = _load_fixture("ohio_lake_excess_funds.pdf")
        leads = self._make_scraper().parse(fixture_bytes)
        assert len(leads) == 2

    def test_case_numbers(self):
        """Case numbers must be extracted in row order."""
        fixture_bytes = _load_fixture("ohio_lake_excess_funds.pdf")
        leads = self._make_scraper().parse(fixture_bytes)
        assert leads[0].case_number == "2021-CV-0234"
        assert leads[1].case_number == "2022-CV-0891"

    def test_surplus_amounts(self):
        """Surplus amounts must be parsed from $-prefixed strings."""
        fixture_bytes = _load_fixture("ohio_lake_excess_funds.pdf")
        leads = self._make_scraper().parse(fixture_bytes)
        assert leads[0].surplus_amount == Decimal("12450.00")
        assert leads[1].surplus_amount == Decimal("5320.75")

    def test_owner_names(self):
        """owner_name must come from the DEBTOR column (index 1)."""
        fixture_bytes = _load_fixture("ohio_lake_excess_funds.pdf")
        leads = self._make_scraper().parse(fixture_bytes)
        assert leads[0].owner_name == "Robert Johnson"
        assert leads[1].owner_name == "Susan Lee"

    def test_property_address_is_none(self):
        """Lake fixture has no address column; property_address must be None."""
        fixture_bytes = _load_fixture("ohio_lake_excess_funds.pdf")
        leads = self._make_scraper().parse(fixture_bytes)
        for lead in leads:
            assert lead.property_address is None

    def test_header_row_excluded(self):
        """Header row must be filtered by skip_rows_containing."""
        fixture_bytes = _load_fixture("ohio_lake_excess_funds.pdf")
        leads = self._make_scraper().parse(fixture_bytes)
        case_numbers = [l.case_number for l in leads]
        assert "CASE NUMBER" not in case_numbers

    def test_state_is_oh(self):
        """Scraper state must be OH."""
        assert self._make_scraper().state == "OH"


# ─── Medina County — ParentPagePdfScraper (4-column) ─────────────────────────


class TestMedinaPdfFixture:
    """Medina County: ParentPagePdfScraper against a real PDF fixture (4-column table).

    Fixture: ohio_medina_excess_funds.pdf
    Column layout:
      0: case_number    (CASE #)
      1: date_deposited (DATE OF DEPOSIT — not captured)
      2: surplus_amount (AMOUNT)
      3: owner_name     (DEF NAME)
    """

    _CONFIG = {
        "pdf_link_selector": "a[href*='.pdf']",
        "pdf_link_pattern": "(?i)Excess.Fund",
        "base_url": "https://medinacountyclerk.org",
        "columns": {
            "case_number": 0,
            "owner_name": 3,
            "surplus_amount": 2,
            "property_address": None,
        },
        "skip_rows_containing": [
            "CASE #",
            "Case #",
            "DEF NAME",
            "AMOUNT",
            "DATE OF DEPOSIT",
            "Medina County",
        ],
    }

    def _make_scraper(self):
        from app.ingestion.parent_page_pdf_scraper import ParentPagePdfScraper

        return ParentPagePdfScraper(
            county_name="Medina",
            source_url="https://medinacountyclerk.org",
            state="OH",
            config=self._CONFIG,
        )

    def test_parse_leads_count(self):
        """Fixture has 2 data rows; parse() must return exactly 2 leads."""
        fixture_bytes = _load_fixture("ohio_medina_excess_funds.pdf")
        leads = self._make_scraper().parse(fixture_bytes)
        assert len(leads) == 2

    def test_case_numbers(self):
        """Case numbers must be extracted from column 0 (CASE #)."""
        fixture_bytes = _load_fixture("ohio_medina_excess_funds.pdf")
        leads = self._make_scraper().parse(fixture_bytes)
        assert leads[0].case_number == "2023-CV-0089"
        assert leads[1].case_number == "2022-CV-0111"

    def test_surplus_amounts(self):
        """Surplus amounts from column 2 (AMOUNT) must be parsed as Decimal."""
        fixture_bytes = _load_fixture("ohio_medina_excess_funds.pdf")
        leads = self._make_scraper().parse(fixture_bytes)
        assert leads[0].surplus_amount == Decimal("9875.00")
        assert leads[1].surplus_amount == Decimal("4200.00")

    def test_owner_names(self):
        """owner_name must come from column 3 (DEF NAME)."""
        fixture_bytes = _load_fixture("ohio_medina_excess_funds.pdf")
        leads = self._make_scraper().parse(fixture_bytes)
        assert leads[0].owner_name == "Patricia Williams"
        assert leads[1].owner_name == "James Brown"

    def test_property_address_is_none(self):
        """Medina fixture has no address column; property_address must be None."""
        fixture_bytes = _load_fixture("ohio_medina_excess_funds.pdf")
        leads = self._make_scraper().parse(fixture_bytes)
        for lead in leads:
            assert lead.property_address is None

    def test_header_row_excluded(self):
        """Header row must be filtered by skip_rows_containing."""
        fixture_bytes = _load_fixture("ohio_medina_excess_funds.pdf")
        leads = self._make_scraper().parse(fixture_bytes)
        case_numbers = [l.case_number for l in leads]
        assert "CASE #" not in case_numbers

    def test_state_is_oh(self):
        """Scraper state must be OH."""
        assert self._make_scraper().state == "OH"


# ─── Fairfield County — ParentPagePdfScraper (7-column) ──────────────────────


class TestFairfieldPdfFixture:
    """Fairfield County: ParentPagePdfScraper against a real PDF fixture (7-column table).

    Fixture: ohio_fairfield_excess_funds.pdf
    Column layout:
      0: case_number       (CASE #)
      1: owner_name        (PARTIES NAME)
      2: last_known_addr   (LAST KNOWN ADDRESS — not captured)
      3: property_address  (PROPERTY ADDRESS)
      4: date_of_sale      (DATE OF SALE — not captured)
      5: date_paid_in      (DATE PAID IN — not captured)
      6: surplus_amount    (AMOUNT)
    """

    _CONFIG = {
        "pdf_link_selector": "a[href*='.pdf']",
        "pdf_link_pattern": "(?i)EXCESS.FUNDS.FROM.TAX",
        "base_url": "https://www.co.fairfield.oh.us",
        "columns": {
            "case_number": 0,
            "owner_name": 1,
            "surplus_amount": 6,
            "property_address": 3,
        },
        "skip_rows_containing": [
            "CASE #",
            "PARTIES",
            "LAST KNOWN",
            "PROPERTY ADDRESS",
            "DATE OF SALE",
            "AMOUNT",
            "Fairfield County",
        ],
    }

    def _make_scraper(self):
        from app.ingestion.parent_page_pdf_scraper import ParentPagePdfScraper

        return ParentPagePdfScraper(
            county_name="Fairfield",
            source_url="https://www.co.fairfield.oh.us/TREASURER/",
            state="OH",
            config=self._CONFIG,
        )

    def test_parse_leads_count(self):
        """Fixture has 2 data rows; parse() must return exactly 2 leads."""
        fixture_bytes = _load_fixture("ohio_fairfield_excess_funds.pdf")
        leads = self._make_scraper().parse(fixture_bytes)
        assert len(leads) == 2

    def test_case_numbers(self):
        """Case numbers must be extracted from column 0."""
        fixture_bytes = _load_fixture("ohio_fairfield_excess_funds.pdf")
        leads = self._make_scraper().parse(fixture_bytes)
        assert leads[0].case_number == "2022-CV-0156"
        assert leads[1].case_number == "2021-CV-0033"

    def test_surplus_amounts(self):
        """Surplus amounts must come from column 6 (AMOUNT)."""
        fixture_bytes = _load_fixture("ohio_fairfield_excess_funds.pdf")
        leads = self._make_scraper().parse(fixture_bytes)
        assert leads[0].surplus_amount == Decimal("22300.00")
        assert leads[1].surplus_amount == Decimal("11800.00")

    def test_owner_names(self):
        """owner_name must come from column 1 (PARTIES NAME)."""
        fixture_bytes = _load_fixture("ohio_fairfield_excess_funds.pdf")
        leads = self._make_scraper().parse(fixture_bytes)
        assert leads[0].owner_name == "Michael Brown"
        assert leads[1].owner_name == "Anna Green"

    def test_property_addresses(self):
        """property_address must come from column 3 (PROPERTY ADDRESS)."""
        fixture_bytes = _load_fixture("ohio_fairfield_excess_funds.pdf")
        leads = self._make_scraper().parse(fixture_bytes)
        assert leads[0].property_address == "123 Maple St Lancaster OH 43130"
        assert leads[1].property_address == "789 Elm St Lancaster OH 43130"

    def test_header_row_excluded(self):
        """Header row must be filtered by skip_rows_containing."""
        fixture_bytes = _load_fixture("ohio_fairfield_excess_funds.pdf")
        leads = self._make_scraper().parse(fixture_bytes)
        case_numbers = [l.case_number for l in leads]
        assert "CASE #" not in case_numbers

    def test_sale_type_is_tax_deed(self):
        """All leads must have sale_type='tax_deed'."""
        fixture_bytes = _load_fixture("ohio_fairfield_excess_funds.pdf")
        leads = self._make_scraper().parse(fixture_bytes)
        for lead in leads:
            assert lead.sale_type == "tax_deed"

    def test_state_is_oh(self):
        """Scraper state must be OH."""
        assert self._make_scraper().state == "OH"


# ─── Montgomery County — PdfScraper (5-column) ───────────────────────────────


class TestMontgomeryPdfFixture:
    """Montgomery County: PdfScraper against a real PDF fixture (5-column table).

    Fixture: ohio_montgomery_excess_funds.pdf
    Column layout:
      0: case_number       (Case Number)
      1: owner_name        (Defendant Name)
      2: property_address  (Property Address)
      3: sale_date         (Sale Date — not captured)
      4: surplus_amount    (Excess Amount)

    Note: The live PDF may be image-based; this fixture tests the text-based
    path only. If the live PDF returns 0 leads, the county should be deactivated
    or switched to OCR (per the activation migration notes).
    """

    _CONFIG = {
        "columns": {
            "case_number": 0,
            "owner_name": 1,
            "surplus_amount": 4,
            "property_address": 2,
        },
        "skip_rows_containing": [
            "Case Number",
            "Case No",
            "Defendant",
            "Montgomery County",
            "Excess Funds",
        ],
    }

    def _make_scraper(self):
        from app.ingestion.pdf_scraper import PdfScraper

        return PdfScraper(
            county_name="Montgomery",
            source_url="https://mcclerkofcourts.org/Downloads/Excess-Funds.pdf",
            state="OH",
            config=self._CONFIG,
        )

    def test_parse_leads_count(self):
        """Fixture has 2 data rows; parse() must return exactly 2 leads."""
        fixture_bytes = _load_fixture("ohio_montgomery_excess_funds.pdf")
        leads = self._make_scraper().parse(fixture_bytes)
        assert len(leads) == 2

    def test_case_numbers(self):
        """Case numbers must be extracted from column 0."""
        fixture_bytes = _load_fixture("ohio_montgomery_excess_funds.pdf")
        leads = self._make_scraper().parse(fixture_bytes)
        assert leads[0].case_number == "2023-CV-00089"
        assert leads[1].case_number == "2022-CV-00201"

    def test_surplus_amounts(self):
        """Surplus amounts must come from column 4 (Excess Amount)."""
        fixture_bytes = _load_fixture("ohio_montgomery_excess_funds.pdf")
        leads = self._make_scraper().parse(fixture_bytes)
        assert leads[0].surplus_amount == Decimal("5620.00")
        assert leads[1].surplus_amount == Decimal("9100.50")

    def test_owner_names(self):
        """owner_name must come from column 1 (Defendant Name)."""
        fixture_bytes = _load_fixture("ohio_montgomery_excess_funds.pdf")
        leads = self._make_scraper().parse(fixture_bytes)
        assert leads[0].owner_name == "David Wilson"
        assert leads[1].owner_name == "Lisa Chen"

    def test_property_addresses(self):
        """property_address must come from column 2 (Property Address)."""
        fixture_bytes = _load_fixture("ohio_montgomery_excess_funds.pdf")
        leads = self._make_scraper().parse(fixture_bytes)
        assert leads[0].property_address == "789 Pine St Dayton OH 45402"
        assert leads[1].property_address == "456 Oak Dr Dayton OH 45405"

    def test_header_row_excluded(self):
        """Header row must be filtered by skip_rows_containing."""
        fixture_bytes = _load_fixture("ohio_montgomery_excess_funds.pdf")
        leads = self._make_scraper().parse(fixture_bytes)
        case_numbers = [l.case_number for l in leads]
        assert "Case Number" not in case_numbers

    def test_sale_type_is_tax_deed(self):
        """All leads must have sale_type='tax_deed'."""
        fixture_bytes = _load_fixture("ohio_montgomery_excess_funds.pdf")
        leads = self._make_scraper().parse(fixture_bytes)
        for lead in leads:
            assert lead.sale_type == "tax_deed"

    def test_state_is_oh(self):
        """Scraper state must be OH."""
        assert self._make_scraper().state == "OH"
